---
  #This is an example yaml file for config, thanks to this one, one doesn't have to hardcode something into the train.py
  #in the batch job file one has just to name the directory of the training data
  epochs: 100                  #number of epochs to train
  loss_function: 'MSE'      #loss function to be used
  optimizer: 'Adam'           #optimizer to be used
  model: 'VAE'                #architecture to be used
  diffusion_model: 'BAS'
  directions: 126              #what is the count of directions?
  device: 'cpu'               #The device the training is done on
  latent: 11                   #latent size of the AE model
  depth: 4
  activation_fct: Tanh
  noise_type: 'gaussian'        #type of added noise
  noise_range: 8             #number of noise distributions
  learning_rate: 0.0001       #learning rate for the training
  D_loss_weight: 0            #weight of the D-loss training !!not implemented yet!!
  batch_size_train: '512'       #batch_size for training
  batch_size_test: '1'        #batch_size for testing
  test_epoch_step: 10          #every how man epochs shall be tested?

  #the below is only relevant for the VAE model
  
  kld_start_epoch: 2          #starting epoch at which the kld loss is used
  kld_restart: False          #bool if the kld should be restartet
  kld_weight_increase: 0.0001     #increase of the weight of the kld_loss
  kld_max_weight: 0.0015          #maximum weight of the kld_loss