N_diff: 126
coil_file_name: 1.0mm_126-dir_R3x3_coils
data_directory: /home/woody/mfqb/mfqb102h/raw/
data_file_name: 1.0mm_126-dir_R3x3_kdat_slice_
decoder_recon: true
device: cpu
diff_enc_file_name: 1.0mm_126-dir_R3x3_dvs
modelPath: /home/hpc/mfqb/mfqb102h/tech_note_vae_diffusion/latrec/training/trained_data/BAS_no_special_layers/
move_directory: /home/woody/mfqb/mfqb102h/no_special_layers/b0_avg/BAS/
muse_recon: false
pat: 2
reg_weight: 3e-10
save_directory: /home/hpc/mfqb/mfqb102h/tech_note_vae_diffusion/latrec/reconstruction/Folder2/
shot_phase_directory: /home/woody/mfqb/mfqb102h/shot_phases/
shot_recon: false
slice_increment: 2
slice_index: 36
vae_denoise_recon: false
vae_reg_recon: false
