---
  #This is an example yaml file for config

  epochs: 100                   # number of epochs to train
  loss_function: 'MSE'          # loss function to be used (implemented are MSE, L1 and Huber)
  optimizer: 'Adam'             # optimizer to be used (implemented are Adam and SGD)
  model: 'VAE'                  # architecture to be used (implemented are DAE and VAE)
  diffusion_model: 'BAS'        # the model equation to be used (implemented DT and BAS)
  mask_usage: True              # should the b0 mask be applied and the custom layers be used?
  device: 'cpu'                 # The device the training is done on ('cpu' or 'cuda')
  latent: 11                    # latent size of the AE model
  depth: 4                      # number of layers +1 of the encoder or decoder (4 corresponds to 3 fully connected layers for encoder then latent space and 3 decoder layers)
  activation_fct: Tanh          # activation function of network (ReLU or Tanh)
  noise_type: 'gaussian'        # type of added noise to signals (gaussian or rician)
  sphere_samples: 60            # number of samples taken from unit sphere
  noise_range: 8                # number of noise distributions added to clean data (set 0 to train only with clean)
  learning_rate: 0.0001         # learning rate for the training
  batch_size_train: '512'       # batch_size for training
  batch_size_test: '1'          # batch_size for testing
  test_epoch_step: 10           # every how man epochs shall be tested?

  dvs_file_path: '../../../data/raw/1.0mm_126-dir_R3x3_dvs.h5' # path to dvs file containing bvalues and gradient vectors of ran sequence